-- # 1 What are the names of all the countries in the country table?
SELECT country_name from country;

-- # 2 What is the total number of customers in the customers table?
SELECT COUNT(customer_id) as num_customers FROM customers;

-- # 3 What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT AVG(age) FROM customers
WHERE can_email = 'yes';

-- # 4 How many orders were made by customers aged 30 or older?
SELECT COUNT(order_id) FROM customers
JOIN orders
ON orders.customer_id = customers.customer_id
WHERE age >= 30;

-- # 5 What is the total revenue generated by each product category?
SELECT category, SUM(price) as tot_revenue FROM products
JOIN baskets
ON products.product_id = baskets.product_id
GROUP BY category;

-- # 6 What is the average price of products in the 'food' category?
SELECT category, AVG(price) FROM products
WHERE category = 'food';

-- # 7 How many orders were made in each sales channel (sales_channel column) in the orders table?
SELECT sales_channel, COUNT(sales_channel) FROM orders
GROUP BY sales_channel;

-- # 8 What is the date of the latest order made by a customer who can receive marketing emails?
SELECT date_shop, can_email FROM customers
JOIN orders
ON customers.customer_id = orders.customer_id
WHERE can_email = 'yes'
ORDER BY date_shop DESC;

-- # 9 What is the name of the country with the highest number of orders?
SELECT country_name, COUNT(orders.country_id) as num_orders FROM orders
JOIN country
ON country.country_id = orders.country_id
GROUP BY country_name
ORDER BY num_orders DESC;

-- # 10 What is the average age of customers who made orders in the 'vitamins' product category?
SELECT category, AVG(age) FROM customers
JOIN orders
ON orders.customer_id = customers.customer_id
JOIN baskets
ON orders.order_id = baskets.order_id
JOIN products
ON baskets.product_id = products.product_id
WHERE category = 'vitamins';